# .goreleaser.yml
before:
  hooks:
    - go mod tidy
    - go generate ./...

project_name: stega

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    main: ./cmd/stega/main.go
    binary: stega
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

release:
  github:
    owner: "brittonhayes"
    name: "stega"

archives:
  - format: tar.gz
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

checksum:
  algorithm: sha256

